version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always

    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  nodeapp:
    build: .
    container_name: nodeapp
    restart: always
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/task
      - JWT_SECRET=your_secret_key
      - JWT_EXP=1h
    depends_on:
      - mongodb

volumes:
  mongo-data:
    driver: local
